face_offset_node:
  ros__parameters:
    camera_input: 2  # 0 for built-in webcam, 2 for external webcam
    
    face_detection:
      scale_factor: 1.1
      min_neighbors: 7

    distance:
      average_eye_distance: 0.063 # in [m]

    camera_parameters:
      sensor_dimensions:
        focal_length: 3.67 # in [mm]
        sensor_width: 4.8 # in [mm]
        sensor_height: 3.6 # in [mm]
      camera_matrix:
        fx: 603.3565980559212 # in [pixel]
        fy: 603.8525136324047 # in [pixel]
        cx: 314.98325947311577 # in [pixel]
        cy: 233.97939039940036 # in [pixel]
      distortion_coefficients: # dimensionless
        [0.07904876200503386, -0.2473724352661824, 1.4961220610951097e-05, 0.0024014898368810893, 0.2125031132173052]

    colors:
      center_dot:
        radius: 5
        color: [0, 255, 0]
        thickness: -1
      face_dot:
        radius: 5
        color: [0, 0, 255]
        thickness: -1
      connection_line:
        color: [255, 255, 255]
        thickness: 3
